### ISSUE TITLE
Line Number Width

### ISSUE THREAD

**Issue by nfarrar** [DandyDev/pelican-bootstrap3#113]
I just quickly set up a site today and decided to use your theme: http://crunk.io/pelican-quickstart.html

The line numbers on the codeblocks aren't wide enough - any any codeblock with double digits is broken.  Any ideas?

**Comment by pablocobelli** [comment]
I'm experiencing the same issue; however I always get wide line numbering blocks no matter the length of the code (in lines). Are there any workarounds to this issue? Thanks for your help.

**Comment by fxer** [comment]
Same issue with short, or really any code blocks. No two line numbering widths are the same on a given page. Is there some custom css that we could inject to the Bootswatch theme to fix the width of line number columns?
