### ISSUE TITLE
Changing Tipue search post URL for better hosting compatibility

### ISSUE THREAD

**Issue by tomkao** [DandyDev/pelican-bootstrap3#145]
The current code for Tipue search require rewrite rule to work properly.
```HTML
<form class="navbar-search" action="/search">
```
In some web host where rewrite rule is not supported (e.g. S3, CloudFiles) the search feature will not be able to function correctly.
Wouldn't it be better to post search data to html file directly?
```HTML
<form class="navbar-search" action="/search.html">
```
The focus here is to have a working out-of-box default configuration rather than supporting every different use case.

**Comment by goanpeca** [comment]
I agree on this, had the exact same issue when testing locally, had to change the action to 

```html
<form class="navbar-search" action="/search.html">
```

But this is also something related to tipue I guess, because I was trying to keep the urls pretty by using the....

```html
/search/index.html 
```

But when using this tipue does not work cause the POST gets called like this

```html
/search?q=pyqt/
```
which yields a 404 error

**Comment by tomkao** [comment]
@goanpeca Have you tried sending your search to `</search/?q=pyqt>` instead?

**Comment by goanpeca** [comment]
@tomkao It does not work like that, because the url is actually `/search/index.html`

**Comment by tomkao** [comment]
@goanpeca Based on my preliminary test, the issue you're reporting seems specific to SimpleHTTPServer (develop_server.sh). When I send a request to URL like `/search?q=pyqt` the SimpleHTTPServer will reply with a 301 and redirect me to `/search?q=pyqt/`. This behavior is not observed on other http servers (Apache & Nginx).

**Comment by DandyDev** [comment]
I personally accept the fact that search is hard to get working locally/in dev mode, but with the proper rewrite rules it works in production, which is the important thing. See dandydev.net for a working example.
