### ISSUE TITLE
How can I disable AddThis feature ?

### ISSUE THREAD

**Issue by drpaneas** [DandyDev/pelican-bootstrap3#162]
I would like my website to load even faster, and it seems that addthis.js takes up some time. I would like to disable this feature, so I went to pelicanconf.py and I commented the two lines:

```
ADDTHIS_PROFILE = 'ra-548e3c553a19ddf3'
ADDTHIS_DATA_TRACK_ADDRESSBAR = False
```

However, after `make html` the websites still loads addthisplugin. Any ideas how can I disable it ?

**Comment by ingwinlu** [comment]
might be a caching issue, try deleting/disabling cache

**Comment by DandyDev** [comment]
Hmmm, that _is_ strange, because `make html` first does a `clean` before building your site again. It is likely to be a Pelican issue though, and not an issue with this theme. Try doing as @ingwinlu says, deleting/disabling cache.
