### ISSUE TITLE
when the line of code is too long the side bar on the right side will flat over the highlight code snippet

### ISSUE THREAD

**Issue by bigpotato920** [DandyDev/pelican-bootstrap3#165]
when I write some code in markdown file and use pygments to highlight the code , if the line of code is too long the side bar on the right side will flat over the highlight code snippet , could you guys help me with that?
![untitled](https://cloud.githubusercontent.com/assets/3883105/6167627/3b932070-b2f8-11e4-9fd8-d3747df6b7dc.png)

PS:I just follow the quick start instructions on the pelican website and paste the pelicanconf.py's content to the markdown file.

**Comment by DandyDev** [comment]
Can you provide a screenshot and a markdown file demonstrating the problem?

**Comment by bigpotato920** [comment]
I add a screenshot of the webpage, the sidebar on right side is floating over the code snippet

**Comment by nagordon** [comment]
I also have a question on this. I really like the sidebar, but it does get in the way on the pages that the content is pure html. My Markdown pages and markdown with liquid tags for ipython notebooks are just thinner. Is there a setting to only show the sidebar on the homepage? The photo bigpotatoe920 is the exact experience I have for my html test page

html input content page generated from ipython notebook
![html_page_generated_from_ipython_notebook](https://cloud.githubusercontent.com/assets/3792276/7191245/22920ba2-e45a-11e4-889a-d37a408c66cd.png)

ipython notebook inserted into markdown page via liquid tags
![2015-04-16 17_01_27-mint-cin running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/3792276/7191286/629579fa-e45a-11e4-82d0-a84e4ea76638.png)

 pure markdown page
![2015-04-16 17_02_47-mint-cin running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/3792276/7191295/7294e8cc-e45a-11e4-83cd-d8fa56217a42.png)



I suppose this is more of a request than a issue. At any rate, 

bootstrap3 is the best pelican theme! Thanks.

**Comment by DandyDev** [comment]
@bigpotato920 and @nagordon could you provide online examples demonstrating the problems you're having? That makes it easier for me to debug :)

**Comment by nagordon** [comment]
@DandyDev please see [html example](http://nagordon.github.io/blog/2015/04/27/html-test/)
and [ipython notebook example](http://nagordon.github.io/blog/2015/04/02/Abaqus-FEA-Scripting-with-python/). The source code is located [here](https://github.com/nagordon/blog)

**Comment by DandyDev** [comment]
I must be missing something, but why would you render the notebook as HTML and then included in the blog source? Why not do it using liquid tags? Then it looks fine, right?

**Comment by nagordon** [comment]
Daan,
     It does work fine/excellent with the liquid tags, but pelican allows
you to render html files (http://docs.getpelican.com/en/3.5.0/content.html).
It is just a different workflow for site generation. I have found that
using html files generated from ipynb files is simpler because all the
links and dependent content are included in the html file.

Is there an option that the sidebar is only shown on the homepage. I think
this would be a sufficient solution to the sidebar covering content from
the html files.




Neal Gordon

**Comment by DandyDev** [comment]
That is currently not possible, but I welcome Pull Requests :)
