### ISSUE TITLE
Is this against HTML syntax?

### ISSUE THREAD

**Issue by caizixian** [DandyDev/pelican-bootstrap3#168]
https://github.com/DandyDev/pelican-bootstrap3/blob/master/templates/base.html#L5

Will result in
```html
<!DOCTYPE html>
<html lang="en"
>
```

**Comment by lgiordani** [comment]
Well, as a matter of fact HTML rendering ignores carriage returns, which is btw the reason we have <p> elements. I may agree that this is not beautiful, but it is not strictly wrong.

**Comment by DandyDev** [comment]
It is valid HTML, and it makes the template at least readable :)
