### ISSUE TITLE
base.html - tipue

### ISSUE THREAD

**Issue by grizz-pl** [DandyDev/pelican-bootstrap3#169]
I'm not sure but there shoud be (base.html line 134):

`<form class="navbar-search" action="/search.html"> `
not
`<form class="navbar-search" action="/search">`

Or i have somthing wronk with conf?

Without this modofication - searching redirect to page which do not exist.

**Comment by python33r** [comment]
I've noticed the same problem.

**Comment by DandyDev** [comment]
In the newest version, this should be fixed :)
