### ISSUE TITLE
Avatar breaks on extra pages.

### ISSUE THREAD

**Issue by Wildcarde** [DandyDev/pelican-bootstrap3#177]
While the avatar icon works fine on the main articles it does not work on anything in the 'pages' folder due to the relative pathing of the file.  These pages are generated as <sitename>/pages/page.html so 'resources/site/avatar.png' is not in a valid location for the rendered pages.

**Comment by mktums** [comment]
Add leading slash to avatar path…

**Comment by DandyDev** [comment]
Seems to work for me, with and without slash. Could you try it _with_ the slash?

**Comment by Wildcarde** [comment]
Well now I feel silly, that worked thanks.
