### ISSUE TITLE
Using Liquid Tags to insert Ipython notebooks without inserting the header 

### ISSUE THREAD

**Issue by nagordon** [DandyDev/pelican-bootstrap3#179]
Daan, I went through installing everything, and used your github repo bootstrap3 theme, but I am getting an error when trying the use liquid tags for inserting ipython notebook. The img liquid tag works but not the notebook

Here is the info for the site on my configuration
https://github.com/nagordon/testsite4/blob/master/content/test_entry.md

Your theme is awesome BTW

Thoughts?

**Comment by nagordon** [comment]
I think I figured it out. ipython was != 2.4.1. I reinstalled with ipython==2.4.1 and it seems to be working. Sorry about the false bug post.

**Comment by DandyDev** [comment]
No problem, glad you got it working!
