### ISSUE TITLE
shariff whatsapp icon

### ISSUE THREAD

**Issue by carlosperate** [DandyDev/pelican-bootstrap3#180]
I cannot get the WhatsApp icon to show when it is enabled in shariff.

I don't have an example online to demostrate the issue, but as an reference from @krid78 (https://github.com/DandyDev/pelican-bootstrap3/pull/163), I cannot see the whatsapp icon there either: http://www.die-kriestens.de/articles/shariff-und-pelicanboostrap3.html

This is what it should look like: http://heiseonline.github.io/shariff/

**Comment by DandyDev** [comment]
Pelican-bootstrap3 was still using an old version of Font-Awesome which didn't have the WhatsApp icon. I've now updated Font-Awesome so it should work now.

**Comment by carlosperate** [comment]
Works great now, thanks Daan!
