### ISSUE TITLE
limit number of lines on IndexPage for each post?

### ISSUE THREAD

**Issue by mgiaco** [DandyDev/pelican-bootstrap3#183]
Does anybody know if it is possible to limit the number of lines on the index page per post?

**Comment by DandyDev** [comment]
Yes. To do so, you have to include a `summary` section in the metadata of your posts. Pelican will use this on the index page, instead of dynamically taking a slice of your post as summary. See: http://docs.getpelican.com/en/latest/content.html?highlight=summary
Hope this helps!

**Comment by mgiaco** [comment]
Oh ... sorry so I think I should read the docs :-)
Thanks for your help!
