### ISSUE TITLE
Disqus is not working for me

### ISSUE THREAD

**Issue by cmarshak** [DandyDev/pelican-bootstrap3#187]
I am new to pelican, and I am trying to follow the directions on your site to install the disqus commenting system.  When I follow your instructions, I get the following error message: "We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."

I then tried to use the `disqus_static` plugin to no avail either.  I tried Isso, but the requirement to understand database management thwarted my more open-source intentions.   

I found this blog post (http://www.blog.talkigy.com/get_disqus-to-work-with-pelican.html), but the suggested fix did not help.

This blog also referenced the troubleshooting disqus site (https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22), but the various templates you have beautifully created seem a bit too difficult for me to alter effectively.

But maybe I am just not understanding what you mean by this: "You can also enable Disqus comments for pages. This is a per-page setting you can control by adding a field `comments` to you pages' metadata. Set it to enabled to *enable* comments for that page. Comment-threads for pages will have an id that is prefixed by 'page-'."

Any ideas/suggestions/references would be appreciated!

http://www.charlie-marshak.net/hi.html

**Comment by cmarshak** [comment]
I used quickstart and for whatever reason SITEURL was not filled out.  I needed to use an absolute path `http://...`

Anyways, thank you for making this well documented theme.  Makes it much easier!

**Comment by DandyDev** [comment]
You're welcome! Glad you found a solution to your problem :)
