### ISSUE TITLE
"Social" icons not displaying?

### ISSUE THREAD

**Issue by dmark** [DandyDev/pelican-bootstrap3#189]
I've seen this on a few of the example sites, in addition to the new one I am working on for myself. Some of the "social" icons are not showing up in the sidebar. The icons in the theme are coloured while the ones in the sidebar are grey-scale so maybe they are not one and the same and I am completely out to lunch. I figured I should ask the experts to confirm my out-to-lunchedness. I have seen the stackoverflow icon on other people's sites so I guess I am wondering, where do the icons come form and is there anything extra I need to do to get them to display? Or is this an actual issue with the theme?

![screenshot_2015-05-20_11-46-09](https://cloud.githubusercontent.com/assets/7488653/7729999/d589b84a-fee5-11e4-8396-7fc1b34a8324.png)

**Comment by DandyDev** [comment]
I'm gonna try this now to see what could be wrong. I'll get back to you asap.

**Comment by DandyDev** [comment]
I found the problem. The theme uses the name of the social network for determining what [FontAwesome](http://fontawesome.io/icons/) icon to show. In FontAwesome StackOverflow is called _stack-overflow_ (with a hyphen), and Last.fm is called _lastfm_.
I pushed some new code to be able to set your own name, but also provide an icon name FontAwesome can understand (https://github.com/DandyDev/pelican-bootstrap3/commit/bb9dca526056b8207743af39def6cf34d083c2c3). See the [updated README](https://github.com/DandyDev/pelican-bootstrap3#sidebar-options).
Hope that helps!
