### ISSUE TITLE
Tags are missing from sidebar

### ISSUE THREAD

**Issue by agrrh-** [DandyDev/pelican-bootstrap3#202]
It could be a good idea to hide by default features which require additional plugins.

Like "Tags" section from sidebar, which require `tag_cloud`.

**Comment by mpancorbo** [comment]
I had similar issue. I'm not sure how I fixed it; one of the steps is activate `tag_cloud` plugin.

**Comment by agrrh-** [comment]
Probably I confused you with a long story, my bad.

Updated the post.

**Comment by TimothyBramlett** [comment]
Wait, so how we fix this issue?  My tags are also not displaying in the side bar.

**Comment by TimothyBramlett** [comment]
Ok, I figured it out.  So, in case it will help anyone else:

In some of the more recent versions of Pelican, the tag_cloud feature which was used to generate the tags from the words in your content has been separated out of the Pelican core repo and put into the Pelican-plugins repo.

The plugins repo can be found here: [https://github.com/getpelican/pelican-plugins](https://github.com/getpelican/pelican-plugins)

Installing the plug-ins is fairly simple.  You just need to clone the pelican-plugins repo into a folder on your computer.  Probably best to put the folder near your project folder but it really shouldn't matter as long as you know where you put it.  

Next inside your pelicanconf.py you will need to add two new settings:

PLUGIN_PATHS = ['/path/to/pelican-plugins']

PLUGINS = ['tag_cloud']

**Comment by DandyDev** [comment]
This was fixed by #196
