### ISSUE TITLE
tipue search failed to generate correct url

### ISSUE THREAD

**Issue by billyzs** [DandyDev/pelican-bootstrap3#220]
Results on the search results page all point to SITEURL/undefined...  Here's an example of the symptom: [http://users.wpi.edu/~szhou2/search.html?q=this](http://users.wpi.edu/~szhou2/search.html?q=this). I do have SEARCH_URL and SITEURL enabled. I've double checked file permission for tipuesearch.json and the json file itself contains the url for the articles in the form of SITEURL/SLUG ... can't really figure out what's wrong. Pelican version 3.6 and server running Apache, 

Thanks!

**Comment by cranmer** [comment]
I also have this problem. Not sure if it is related to having root of site
being deeper than domain/

**Comment by billyzs** [comment]
Hey Kyle - I can't rule that out, I have the same setup with site deeper
than domain. What have you tried to make tipue work? Out of curiosity, is
Disqus working for you?

**Comment by spacehobo** [comment]
I had this problem, and solved it by updating tipue to v5.0 per https://github.com/DandyDev/pelican-bootstrap3/pull/198

**Comment by doctorwidget** [comment]
Same here -- I was getting results that showed the correct title and text, but with undefined URLs. Changing Tipue from version 4.0 to version 5.0 solved the problem.

**Comment by billyzs** [comment]
Manually copying the v5.0 files helped, thanks guys.

**Comment by tmpsantos** [comment]
> Manually copying the v5.0 files helped, thanks guys.

That also worked for me.

**Comment by tmpsantos** [comment]
Noticed that are already 2 PR pending fixing this issue.
